[package]
name = "datamatrix"
version = "0.3.3"
authors = ["Jannik Schürg <jannik.schuerg+crates@posteo.de>"]
edition = "2024"
rust-version = "1.95"
readme = "README.md"
license = "Apache-2.0 OR MIT"
description = "Optimizing encoder ile Data Matrix (ECC 200) decoding ve encoding"
repository = "https://github.com/jannschu/datamatrix-rs/"
categories = ["encoding"]
keywords = ["codematrix", "datamatrix", "semacode", "no_std"]

[lints.clippy]
indexing_slicing = "deny"
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
unreachable = "deny"
todo = "deny"
unimplemented = "deny"
exit = "deny"

[features]
default = []
extended_eci = ["encoding_rs"]

[dependencies]
arrayvec = { version = "0.7.8", default-features = false }
flagset = "0.4.7"
encoding_rs = { version = "0.8.35", optional = true }

[dev-dependencies]
image = { version = "0.25.10", default-features = false, features = ["png"] }
krilla = { version = "0.8.2", default-features = false }
qrcode2 = { package = "qrcode", path = "../qrcode-rust", default-features = false }
enum-iterator = "2.3.0"
pretty_assertions = "1.4.1"
proptest = "1.11.0"
